# Generated by Django 5.1.6 on 2025-03-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_featuredplayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredplayer',
            old_name='image',
            new_name='image_url',
        ),
    ]
