# Generated by Django 5.1.6 on 2025-03-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_image_featuredplayer_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredplayer',
            old_name='image_url',
            new_name='image',
        ),
    ]
