# Generated by Django 5.1.6 on 2025-04-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_season_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='season',
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos/'),
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
