# Generated by Django 5.1.6 on 2025-04-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_url', models.URLField()),
                ('match_title', models.CharField(max_length=200)),
                ('is_live', models.BooleanField(default=False)),
            ],
        ),
    ]
