# Generated by Django 5.1.6 on 2025-04-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_livematch_is_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livematch',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
