# Generated by Django 5.1.6 on 2025-04-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_livematch_is_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='video',
        ),
        migrations.AddField(
            model_name='news',
            name='news_photo',
            field=models.ImageField(blank=True, null=True, upload_to='news_photos/'),
        ),
    ]
