# Generated by Django 5.1.6 on 2025-04-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_news_video_news_news_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='source_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
