# Generated by Django 5.1.6 on 2025-03-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_news_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='players/')),
                ('bio', models.TextField()),
                ('goals_scored', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
