# Generated by Django 5.1.6 on 2025-04-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_club_season_alter_club_logo_delete_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('imageUrl', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
