# Generated by Django 5.1.6 on 2025-04-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_livematch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livematch',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
    ]
