# Generated by Django 5.1.6 on 2025-05-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_season_playerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='season',
        ),
    ]
