# Generated by Django 5.0.1 on 2024-11-01 05:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0092_rename_match_matchday"),
        ("football", "0101_alter_fixtureteam_team"),
    ]

    operations = []
