# Generated by Django 5.0.1 on 2024-11-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('player', 'Player'), ('coach', 'Coach'), ('admin', 'Admin')], max_length=10),
        ),
    ]
