# Generated by Django 5.0.1 on 2024-11-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('club', 'Club'), ('fan', 'Fan'), ('player', 'Player')], max_length=10),
        ),
    ]
