# Generated by Django 5.0.1 on 2024-12-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('coach', 'Coach'), ('admin', 'Admin'), ('player', 'Player')], max_length=10),
        ),
    ]
