# Generated by Django 5.0.1 on 2025-01-09 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('coach_name', models.CharField(max_length=255)),
                ('coach_phone', models.CharField(max_length=15)),
                ('coach_email', models.EmailField(max_length=254)),
                ('manager_name', models.CharField(max_length=255)),
                ('manager_phone', models.CharField(max_length=15)),
                ('manager_email', models.EmailField(max_length=254)),
                ('team_category', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('youth', 'Youth')], max_length=50)),
                ('num_players', models.PositiveIntegerField()),
                ('home_ground', models.CharField(max_length=255)),
                ('training_ground_needs', models.TextField()),
                ('equipment_needed', models.TextField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Coach', 'Coach'), ('Player', 'Player')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
