name: Notify Contributors

on:
  push:
    branches:
      - main
      - api-dev
  pull_request:
    branches:
      - main
      - api-dev

jobs:
  notify-contributors:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch unique contributors
      run: |
        # Fetch all unique contributors from commit logs for the past commits
        CONTRIBUTORS=$(git log --pretty=format:"%ae" | sort | uniq)

    - name: Notify Contributors via Email (SendGrid)
      run: |
        # Send email notification to each contributor
        for contributor in $CONTRIBUTORS; do
          echo "Notifying contributor: $contributor about a new commit or pull request."

          # Customize the email body and subject for each contributor
          EMAIL_SUBJECT="New Commit or Pull Request in Repository"
          EMAIL_BODY="Hello ${contributor},\n\nA new commit or pull request has been made to the repository. Please check the repository for the latest updates.\n\nBest, GitHub Actions Bot."

          # Send the email via SendGrid API
          curl -X POST https://api.sendgrid.com/v3/mail/send \
            -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d @- << EOF
{
  "personalizations": [
    {
      "to": [
        {
          "email": "${contributor}"
        }
      ],
      "subject": "${EMAIL_SUBJECT}"
    }
  ],
  "from": {
    "email": "your-email@example.com"
  },
  "content": [
    {
      "type": "text/plain",
      "value": "${EMAIL_BODY}"
    }
  ]
}
EOF
        done

    - name: Provide Summary
      run: |
        echo "A new commit or PR has been made. Contributors have been notified via email."
